version: '2'

services:
  db:
    image: mongo:4.2.6-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - db:/data/db
    ports:
      - "27017:27017"

  strapi:
    image: strapi/strapi:3.0.0-beta.20.2-node12-alpine
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 27017
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
    # volumes:
    #   - ./app:/srv/app
    depends_on:
      - "db"
    links:
      - "db:db"
    ports:
      - "1337:1337"


volumes:
  db:
    driver: local
